# Generated by Django 5.1.1 on 2025-05-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='con_us',
            name='massage',
            field=models.TextField(max_length=500),
        ),
    ]
