# Generated by Django 5.1.1 on 2025-05-30 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0002_alter_con_us_massage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='con_us',
            old_name='massage',
            new_name='message',
        ),
    ]
