# Generated by Django 5.1.1 on 2025-06-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mstName', models.CharField(max_length=100, unique=True)),
                ('mstEmail', models.EmailField(max_length=254, unique=True)),
                ('mstPassword', models.CharField(max_length=100)),
                ('mstStatus', models.BooleanField(default=True)),
            ],
        ),
    ]
