# Generated by Django 5.1.1 on 2025-06-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(max_length=100)),
                ('catImage', models.ImageField(upload_to='catImage')),
                ('catStatus', models.BooleanField(default=True)),
                ('catSlug', models.SlugField()),
            ],
        ),
    ]
