# Generated by Django 5.1.1 on 2025-06-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_categorymaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdName', models.CharField(max_length=100)),
                ('prdDescription', models.TextField()),
                ('prdPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prdIsoffer', models.BooleanField(default=False)),
                ('prdOfferPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prdImage', models.ImageField(upload_to='prdImage')),
                ('prdStatus', models.BooleanField(default=True)),
                ('prdMailDes', models.TextField()),
            ],
        ),
    ]
