# Generated by Django 5.1.1 on 2025-06-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prdIsoffer',
            field=models.BooleanField(default=True),
        ),
    ]
