# Generated by Django 5.1.1 on 2025-06-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_alter_product_prdisoffer_alter_product_prdstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prdIsoffer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='prdStatus',
            field=models.BooleanField(default=False),
        ),
    ]
