# Generated by Django 5.2 on 2025-07-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_alter_product_prdisoffer_alter_product_prdstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prdFeature',
            field=models.BooleanField(default=False),
        ),
    ]
