<<<<<<< HEAD
# Generated by Django 5.2 on 2025-07-16 03:20
=======
# Generated by Django 5.1.1 on 2025-07-16 06:23
>>>>>>> de1bc3b6e4a8f1ef05c08c251033e3cd2bdd649e

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_alter_product_prdisoffer_alter_product_prdstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prdFeature',
            field=models.BooleanField(default=False),
        ),
    ]
