
# Generated by Django 5.2 on 2025-07-17 03:20

# Generated by Django 5.1.1 on 2025-07-17 06:47


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_product_prdfeature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prdStatus',
            new_name='prdLatest',
        ),
    ]
