<<<<<<< HEAD
# Generated by Django 5.2 on 2025-07-20 03:21
=======
# Generated by Django 5.1.1 on 2025-07-21 07:20
>>>>>>> de1bc3b6e4a8f1ef05c08c251033e3cd2bdd649e

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_rename_prdstatus_product_prdlatest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prdBlog',
            field=models.BooleanField(default=False),
        ),
    ]
