# Generated by Django 5.2 on 2025-09-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0010_product_prdblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prdCatFemale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='prdCatMale',
            field=models.BooleanField(default=False),
        ),
    ]
